from time import sleep
print("Guess the number")
sleep(3)
print('Multyply the number with 2')
sleep(3)
print('add 8 with the number')
sleep(3)
print("divide the whole number with 2")
sleep(3)
print("substract the guessed number with the result")
sleep(3)
print("Your guessed number is 4")
